USE SISTEMAEVALUACION;

SELECT * FROM USUARIOS;
SELECT * FROM PERFILES;
SELECT * FROM MODULOS;

INSERT INTO PERFILES VALUES(1, 'DOCENTE', 'ACT');
INSERT INTO PERFILES VALUES(2, 'JEFEAREA', 'ACT');
INSERT INTO PERFILES VALUES(3, 'DIRECTOR', 'ACT');

begin transaction;
INSERT INTO MODULOS VALUES(1,'REDES','ACT');

INSERT INTO USUARIOS VALUES(1, 'pguerra', 'pguerra@kruger.com.ec','Pablo Guerra', 1,'ACT', 'password01',1);
INSERT INTO USUARIOS VALUES(2, 'jlopez', 'jlopez@ups.edu.ec','Jorge Lopez', 2,'ACT', 'password01',1);
INSERT INTO USUARIOS VALUES(3, 'pprieto', 'pprieto@ups.edu.ec','Patsy Prieto', 3,'ACT', 'password01',1);


delete from criterios;
INSERT INTO CRITERIOS VALUES (1, 'ENTREGA', 'ACT', 'ENTREGA', 'Entrega de la tarea');
INSERT INTO CRITERIOS VALUES (2, 'CALIFICACION', 'ACT', 'CALIFICACION','Valor de la tarea');
INSERT INTO CRITERIOS VALUES (3, 'FECHAENVIO', 'ACT', 'FECHA ENVIO', 'Fecha en la que se envió la tarea');

INSERT INTO TIPOSTAREAS VALUES(1,'TAREA','TAREA NORMAL','ACT');
INSERT INTO TIPOSTAREAS VALUES(2,'REUNION','REUNIONES','ACT');

SELECT * FROM TIPOSTAREAS;
SELECT * FROM CRITERIOS;
SELECT * FROM CRITERIOS left JOIN CATALOGOCRITERIO ON CRITERIOS.idCriterio = CATALOGOCRITERIO.idCriterio;
SELECT * FROM CATALOGOCRITERIO;

SELECT * FROM TAREAS;
SELECT * FROM TAREASUSUARIOS;
SELECT * FROM USUARIOS;
commit;
SELECT * FROM TAREASUSUARIOS AS TARUS LEFT JOIN TAREAS ON TAREAS.idTarea = TARUS.idTarea
WHERE TARUS.idUsuario = 2;

DELETE FROM TAREAS;
DELETE FROM TAREASUSUARIOS;


SELECT * FROM TAREASUSUARIOS LEFT JOIN TAREAS ON TAREAS.idTarea = TAREASuSUARIOS.idTarea WHERE TAREASuSUARIOS.IDuSUARIO = 1;


DELETE FROM TAREAS;
DELETE FROM TAREASUSUARIOS;


--UPDATE TAREASUSUARIOS SET FECHAENVIO = CURRENT TIMESTAMP WHERE IDTAREAUSUARIO = 11;
--UPDATE TAREASUSUARIOS SET ObservacionCalificacion = NULL WHERE IDTAREAUSUARIO = 57;


select * from tareasusuarios;
select * from tareas;


/***** consulta tareas calificadas de un usuario (Mis notas)  **/
SELECT * FROM TAREASUSUARIOS AS TARUSU
INNER JOIN TAREAS ON TAREAS.IDTAREA = TARUSU.idTarea
INNER JOIN usuarios ON USUARIOS.idUsuario = TARUSU.idUsuario
WHERE TARUSU.ESTADO = 'CLF'
AND TARUSU.IDUSUARIO = 1;

/*********** consulta todas las tareas calificadas de todos los usuarios ************/
SELECT * FROM TAREASUSUARIOS AS TARUSU
INNER JOIN TAREAS ON TAREAS.IDTAREA = TARUSU.idTarea
INNER JOIN usuarios ON USUARIOS.idUsuario = TARUSU.idUsuario
WHERE TARUSU.ESTADO = 'CLF';

/************* consulta todas las tareas enviadas de un usuario***************/
SELECT * FROM TAREASUSUARIOS AS TARUSU
INNER JOIN TAREAS ON TAREAS.IDTAREA = TARUSU.idTarea
INNER JOIN usuarios ON USUARIOS.idUsuario = TARUSU.idUsuario 
WHERE TARUSU.ESTADO = 'ENV'
AND TARUSU.IDUSURAIO = 1;

